#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Service
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Paradise")]
	public partial class ParadiseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertRESERVA(RESERVA instance);
    partial void UpdateRESERVA(RESERVA instance);
    partial void DeleteRESERVA(RESERVA instance);
    #endregion
		
		public ParadiseDataContext() : 
				base(global::Paradise.Service.Properties.Settings.Default.ParadiseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ParadiseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParadiseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParadiseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParadiseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RESERVA> RESERVA
		{
			get
			{
				return this.GetTable<RESERVA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RESERVA")]
	public partial class RESERVA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ResNro;
		
		private string _ResUsuIng;
		
		private System.Nullable<short> _ResHab;
		
		private System.Nullable<System.DateTime> _ResFecIng;
		
		private string _ResHorIng;
		
		private string _ResMaqIng;
		
		private string _ResUsuMod;
		
		private System.Nullable<int> _ResPaxTit;
		
		private string _ResMaqMod;
		
		private System.Nullable<System.DateTime> _ResFecMod;
		
		private string _ResHorMod;
		
		private string _ResUsuCan;
		
		private System.Nullable<System.DateTime> _ResFecCan;
		
		private string _ResHorCan;
		
		private string _ResMaqCan;
		
		private string _ResQuien;
		
		private System.Nullable<short> _ResSerObs;
		
		private System.Nullable<char> _ResPago;
		
		private string _ResTel;
		
		private string _ResFax;
		
		private string _ResResPor;
		
		private System.Nullable<System.DateTime> _ResFecEnt;
		
		private System.Nullable<System.DateTime> _ResFecSal;
		
		private string _ResEsta;
		
		private string _ResProced;
		
		private System.Nullable<short> _RHConLin;
		
		private string _ResPlan;
		
		private System.Nullable<short> _ResConSen;
		
		private System.Nullable<char> _ResConfirm;
		
		private System.Nullable<System.DateTime> _ResFecConf;
		
		private string _ResHorConf;
		
		private string _ResMotCan;
		
		private System.Nullable<short> _ResPorDto;
		
		private System.Nullable<short> _DescId;
		
		private System.Nullable<int> _ResEmpPaga;
		
		private string _ResDestino;
		
		private System.Nullable<int> _ResConRoo;
		
		private System.Nullable<char> _ResTarifCar;
		
		private System.Nullable<short> _ResMonFact;
		
		private System.Nullable<short> _ResCamMat;
		
		private System.Nullable<short> _ResCamSin;
		
		private System.Nullable<short> _ResCamCun;
		
		private string _ResHoraEntrada;
		
		private string _ResGruId;
		
		private System.Nullable<int> _AgeViaId;
		
		private System.Nullable<char> _ResCambioDatAgencia;
		
		private System.Nullable<int> _ResPagaHospedaje;
		
		private string _ResFecEntHor;
		
		private System.Nullable<short> _ResMucLinObs;
		
		private string _ResMail;
		
		private System.Nullable<char> _ResHabiaSenia;
		
		private System.Nullable<short> _ResHisHabNumAnt;
		
		private string _ResHisTarIdAnt;
		
		private System.Nullable<short> _ResHisTarMonIdAnt;
		
		private System.Nullable<decimal> _ResHisTarImporteAnt;
		
		private System.Nullable<char> _ResConfPorMail;
		
		private System.Nullable<int> _ResEMailId;
		
		private System.Nullable<char> _ResDesAplicableA;
		
		private System.Nullable<short> _ResCantPax;
		
		private System.Nullable<int> _TipOcuId;
		
		private System.Nullable<char> _ResFichaDeIngreso;
		
		private string _ResMotivoAlojamiento;
		
		private System.Nullable<char> _ResLateCheckOut;
		
		private System.Nullable<short> _ResDesayunos;
		
		private string _ResVoucherAgencia;
		
		private System.Nullable<int> _ResCanFacIdNoShow;
		
		private System.Nullable<char> _ResCanNoShow;
		
		private System.Nullable<decimal> _ResSeniaUtilizada;
		
		private string _ResAutoMatricula;
		
		private string _ResAutoColor;
		
		private string _ResAutoModelo;
		
		private string _ResAutoMarca;
		
		private System.Nullable<char> _ResFechaConfirmacionMovible;
		
		private System.Nullable<System.DateTime> _ResFechaConfirmacion;
		
		private string _ResMaqVer;
		
		private string _ResUsuVer;
		
		private string _ResHorVer;
		
		private System.Nullable<System.DateTime> _ResFecVer;
		
		private System.Nullable<char> _ResVerificada;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResNroChanging(int value);
    partial void OnResNroChanged();
    partial void OnResUsuIngChanging(string value);
    partial void OnResUsuIngChanged();
    partial void OnResHabChanging(System.Nullable<short> value);
    partial void OnResHabChanged();
    partial void OnResFecIngChanging(System.Nullable<System.DateTime> value);
    partial void OnResFecIngChanged();
    partial void OnResHorIngChanging(string value);
    partial void OnResHorIngChanged();
    partial void OnResMaqIngChanging(string value);
    partial void OnResMaqIngChanged();
    partial void OnResUsuModChanging(string value);
    partial void OnResUsuModChanged();
    partial void OnResPaxTitChanging(System.Nullable<int> value);
    partial void OnResPaxTitChanged();
    partial void OnResMaqModChanging(string value);
    partial void OnResMaqModChanged();
    partial void OnResFecModChanging(System.Nullable<System.DateTime> value);
    partial void OnResFecModChanged();
    partial void OnResHorModChanging(string value);
    partial void OnResHorModChanged();
    partial void OnResUsuCanChanging(string value);
    partial void OnResUsuCanChanged();
    partial void OnResFecCanChanging(System.Nullable<System.DateTime> value);
    partial void OnResFecCanChanged();
    partial void OnResHorCanChanging(string value);
    partial void OnResHorCanChanged();
    partial void OnResMaqCanChanging(string value);
    partial void OnResMaqCanChanged();
    partial void OnResQuienChanging(string value);
    partial void OnResQuienChanged();
    partial void OnResSerObsChanging(System.Nullable<short> value);
    partial void OnResSerObsChanged();
    partial void OnResPagoChanging(System.Nullable<char> value);
    partial void OnResPagoChanged();
    partial void OnResTelChanging(string value);
    partial void OnResTelChanged();
    partial void OnResFaxChanging(string value);
    partial void OnResFaxChanged();
    partial void OnResResPorChanging(string value);
    partial void OnResResPorChanged();
    partial void OnResFecEntChanging(System.Nullable<System.DateTime> value);
    partial void OnResFecEntChanged();
    partial void OnResFecSalChanging(System.Nullable<System.DateTime> value);
    partial void OnResFecSalChanged();
    partial void OnResEstaChanging(string value);
    partial void OnResEstaChanged();
    partial void OnResProcedChanging(string value);
    partial void OnResProcedChanged();
    partial void OnRHConLinChanging(System.Nullable<short> value);
    partial void OnRHConLinChanged();
    partial void OnResPlanChanging(string value);
    partial void OnResPlanChanged();
    partial void OnResConSenChanging(System.Nullable<short> value);
    partial void OnResConSenChanged();
    partial void OnResConfirmChanging(System.Nullable<char> value);
    partial void OnResConfirmChanged();
    partial void OnResFecConfChanging(System.Nullable<System.DateTime> value);
    partial void OnResFecConfChanged();
    partial void OnResHorConfChanging(string value);
    partial void OnResHorConfChanged();
    partial void OnResMotCanChanging(string value);
    partial void OnResMotCanChanged();
    partial void OnResPorDtoChanging(System.Nullable<short> value);
    partial void OnResPorDtoChanged();
    partial void OnDescIdChanging(System.Nullable<short> value);
    partial void OnDescIdChanged();
    partial void OnResEmpPagaChanging(System.Nullable<int> value);
    partial void OnResEmpPagaChanged();
    partial void OnResDestinoChanging(string value);
    partial void OnResDestinoChanged();
    partial void OnResConRooChanging(System.Nullable<int> value);
    partial void OnResConRooChanged();
    partial void OnResTarifCarChanging(System.Nullable<char> value);
    partial void OnResTarifCarChanged();
    partial void OnResMonFactChanging(System.Nullable<short> value);
    partial void OnResMonFactChanged();
    partial void OnResCamMatChanging(System.Nullable<short> value);
    partial void OnResCamMatChanged();
    partial void OnResCamSinChanging(System.Nullable<short> value);
    partial void OnResCamSinChanged();
    partial void OnResCamCunChanging(System.Nullable<short> value);
    partial void OnResCamCunChanged();
    partial void OnResHoraEntradaChanging(string value);
    partial void OnResHoraEntradaChanged();
    partial void OnResGruIdChanging(string value);
    partial void OnResGruIdChanged();
    partial void OnAgeViaIdChanging(System.Nullable<int> value);
    partial void OnAgeViaIdChanged();
    partial void OnResCambioDatAgenciaChanging(System.Nullable<char> value);
    partial void OnResCambioDatAgenciaChanged();
    partial void OnResPagaHospedajeChanging(System.Nullable<int> value);
    partial void OnResPagaHospedajeChanged();
    partial void OnResFecEntHorChanging(string value);
    partial void OnResFecEntHorChanged();
    partial void OnResMucLinObsChanging(System.Nullable<short> value);
    partial void OnResMucLinObsChanged();
    partial void OnResMailChanging(string value);
    partial void OnResMailChanged();
    partial void OnResHabiaSeniaChanging(System.Nullable<char> value);
    partial void OnResHabiaSeniaChanged();
    partial void OnResHisHabNumAntChanging(System.Nullable<short> value);
    partial void OnResHisHabNumAntChanged();
    partial void OnResHisTarIdAntChanging(string value);
    partial void OnResHisTarIdAntChanged();
    partial void OnResHisTarMonIdAntChanging(System.Nullable<short> value);
    partial void OnResHisTarMonIdAntChanged();
    partial void OnResHisTarImporteAntChanging(System.Nullable<decimal> value);
    partial void OnResHisTarImporteAntChanged();
    partial void OnResConfPorMailChanging(System.Nullable<char> value);
    partial void OnResConfPorMailChanged();
    partial void OnResEMailIdChanging(System.Nullable<int> value);
    partial void OnResEMailIdChanged();
    partial void OnResDesAplicableAChanging(System.Nullable<char> value);
    partial void OnResDesAplicableAChanged();
    partial void OnResCantPaxChanging(System.Nullable<short> value);
    partial void OnResCantPaxChanged();
    partial void OnTipOcuIdChanging(System.Nullable<int> value);
    partial void OnTipOcuIdChanged();
    partial void OnResFichaDeIngresoChanging(System.Nullable<char> value);
    partial void OnResFichaDeIngresoChanged();
    partial void OnResMotivoAlojamientoChanging(string value);
    partial void OnResMotivoAlojamientoChanged();
    partial void OnResLateCheckOutChanging(System.Nullable<char> value);
    partial void OnResLateCheckOutChanged();
    partial void OnResDesayunosChanging(System.Nullable<short> value);
    partial void OnResDesayunosChanged();
    partial void OnResVoucherAgenciaChanging(string value);
    partial void OnResVoucherAgenciaChanged();
    partial void OnResCanFacIdNoShowChanging(System.Nullable<int> value);
    partial void OnResCanFacIdNoShowChanged();
    partial void OnResCanNoShowChanging(System.Nullable<char> value);
    partial void OnResCanNoShowChanged();
    partial void OnResSeniaUtilizadaChanging(System.Nullable<decimal> value);
    partial void OnResSeniaUtilizadaChanged();
    partial void OnResAutoMatriculaChanging(string value);
    partial void OnResAutoMatriculaChanged();
    partial void OnResAutoColorChanging(string value);
    partial void OnResAutoColorChanged();
    partial void OnResAutoModeloChanging(string value);
    partial void OnResAutoModeloChanged();
    partial void OnResAutoMarcaChanging(string value);
    partial void OnResAutoMarcaChanged();
    partial void OnResFechaConfirmacionMovibleChanging(System.Nullable<char> value);
    partial void OnResFechaConfirmacionMovibleChanged();
    partial void OnResFechaConfirmacionChanging(System.Nullable<System.DateTime> value);
    partial void OnResFechaConfirmacionChanged();
    partial void OnResMaqVerChanging(string value);
    partial void OnResMaqVerChanged();
    partial void OnResUsuVerChanging(string value);
    partial void OnResUsuVerChanged();
    partial void OnResHorVerChanging(string value);
    partial void OnResHorVerChanged();
    partial void OnResFecVerChanging(System.Nullable<System.DateTime> value);
    partial void OnResFecVerChanged();
    partial void OnResVerificadaChanging(System.Nullable<char> value);
    partial void OnResVerificadaChanged();
    #endregion
		
		public RESERVA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResNro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ResNro
		{
			get
			{
				return this._ResNro;
			}
			set
			{
				if ((this._ResNro != value))
				{
					this.OnResNroChanging(value);
					this.SendPropertyChanging();
					this._ResNro = value;
					this.SendPropertyChanged("ResNro");
					this.OnResNroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResUsuIng", DbType="Char(10)")]
		public string ResUsuIng
		{
			get
			{
				return this._ResUsuIng;
			}
			set
			{
				if ((this._ResUsuIng != value))
				{
					this.OnResUsuIngChanging(value);
					this.SendPropertyChanging();
					this._ResUsuIng = value;
					this.SendPropertyChanged("ResUsuIng");
					this.OnResUsuIngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHab", DbType="SmallInt")]
		public System.Nullable<short> ResHab
		{
			get
			{
				return this._ResHab;
			}
			set
			{
				if ((this._ResHab != value))
				{
					this.OnResHabChanging(value);
					this.SendPropertyChanging();
					this._ResHab = value;
					this.SendPropertyChanged("ResHab");
					this.OnResHabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFecIng", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResFecIng
		{
			get
			{
				return this._ResFecIng;
			}
			set
			{
				if ((this._ResFecIng != value))
				{
					this.OnResFecIngChanging(value);
					this.SendPropertyChanging();
					this._ResFecIng = value;
					this.SendPropertyChanged("ResFecIng");
					this.OnResFecIngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHorIng", DbType="Char(8)")]
		public string ResHorIng
		{
			get
			{
				return this._ResHorIng;
			}
			set
			{
				if ((this._ResHorIng != value))
				{
					this.OnResHorIngChanging(value);
					this.SendPropertyChanging();
					this._ResHorIng = value;
					this.SendPropertyChanged("ResHorIng");
					this.OnResHorIngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResMaqIng", DbType="Char(20)")]
		public string ResMaqIng
		{
			get
			{
				return this._ResMaqIng;
			}
			set
			{
				if ((this._ResMaqIng != value))
				{
					this.OnResMaqIngChanging(value);
					this.SendPropertyChanging();
					this._ResMaqIng = value;
					this.SendPropertyChanged("ResMaqIng");
					this.OnResMaqIngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResUsuMod", DbType="Char(10)")]
		public string ResUsuMod
		{
			get
			{
				return this._ResUsuMod;
			}
			set
			{
				if ((this._ResUsuMod != value))
				{
					this.OnResUsuModChanging(value);
					this.SendPropertyChanging();
					this._ResUsuMod = value;
					this.SendPropertyChanged("ResUsuMod");
					this.OnResUsuModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResPaxTit", DbType="Int")]
		public System.Nullable<int> ResPaxTit
		{
			get
			{
				return this._ResPaxTit;
			}
			set
			{
				if ((this._ResPaxTit != value))
				{
					this.OnResPaxTitChanging(value);
					this.SendPropertyChanging();
					this._ResPaxTit = value;
					this.SendPropertyChanged("ResPaxTit");
					this.OnResPaxTitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResMaqMod", DbType="Char(20)")]
		public string ResMaqMod
		{
			get
			{
				return this._ResMaqMod;
			}
			set
			{
				if ((this._ResMaqMod != value))
				{
					this.OnResMaqModChanging(value);
					this.SendPropertyChanging();
					this._ResMaqMod = value;
					this.SendPropertyChanged("ResMaqMod");
					this.OnResMaqModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFecMod", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResFecMod
		{
			get
			{
				return this._ResFecMod;
			}
			set
			{
				if ((this._ResFecMod != value))
				{
					this.OnResFecModChanging(value);
					this.SendPropertyChanging();
					this._ResFecMod = value;
					this.SendPropertyChanged("ResFecMod");
					this.OnResFecModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHorMod", DbType="Char(8)")]
		public string ResHorMod
		{
			get
			{
				return this._ResHorMod;
			}
			set
			{
				if ((this._ResHorMod != value))
				{
					this.OnResHorModChanging(value);
					this.SendPropertyChanging();
					this._ResHorMod = value;
					this.SendPropertyChanged("ResHorMod");
					this.OnResHorModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResUsuCan", DbType="Char(10)")]
		public string ResUsuCan
		{
			get
			{
				return this._ResUsuCan;
			}
			set
			{
				if ((this._ResUsuCan != value))
				{
					this.OnResUsuCanChanging(value);
					this.SendPropertyChanging();
					this._ResUsuCan = value;
					this.SendPropertyChanged("ResUsuCan");
					this.OnResUsuCanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFecCan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResFecCan
		{
			get
			{
				return this._ResFecCan;
			}
			set
			{
				if ((this._ResFecCan != value))
				{
					this.OnResFecCanChanging(value);
					this.SendPropertyChanging();
					this._ResFecCan = value;
					this.SendPropertyChanged("ResFecCan");
					this.OnResFecCanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHorCan", DbType="Char(8)")]
		public string ResHorCan
		{
			get
			{
				return this._ResHorCan;
			}
			set
			{
				if ((this._ResHorCan != value))
				{
					this.OnResHorCanChanging(value);
					this.SendPropertyChanging();
					this._ResHorCan = value;
					this.SendPropertyChanged("ResHorCan");
					this.OnResHorCanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResMaqCan", DbType="Char(20)")]
		public string ResMaqCan
		{
			get
			{
				return this._ResMaqCan;
			}
			set
			{
				if ((this._ResMaqCan != value))
				{
					this.OnResMaqCanChanging(value);
					this.SendPropertyChanging();
					this._ResMaqCan = value;
					this.SendPropertyChanged("ResMaqCan");
					this.OnResMaqCanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResQuien", DbType="Char(60)")]
		public string ResQuien
		{
			get
			{
				return this._ResQuien;
			}
			set
			{
				if ((this._ResQuien != value))
				{
					this.OnResQuienChanging(value);
					this.SendPropertyChanging();
					this._ResQuien = value;
					this.SendPropertyChanged("ResQuien");
					this.OnResQuienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResSerObs", DbType="SmallInt")]
		public System.Nullable<short> ResSerObs
		{
			get
			{
				return this._ResSerObs;
			}
			set
			{
				if ((this._ResSerObs != value))
				{
					this.OnResSerObsChanging(value);
					this.SendPropertyChanging();
					this._ResSerObs = value;
					this.SendPropertyChanged("ResSerObs");
					this.OnResSerObsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResPago", DbType="Char(1)")]
		public System.Nullable<char> ResPago
		{
			get
			{
				return this._ResPago;
			}
			set
			{
				if ((this._ResPago != value))
				{
					this.OnResPagoChanging(value);
					this.SendPropertyChanging();
					this._ResPago = value;
					this.SendPropertyChanged("ResPago");
					this.OnResPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResTel", DbType="Char(15)")]
		public string ResTel
		{
			get
			{
				return this._ResTel;
			}
			set
			{
				if ((this._ResTel != value))
				{
					this.OnResTelChanging(value);
					this.SendPropertyChanging();
					this._ResTel = value;
					this.SendPropertyChanged("ResTel");
					this.OnResTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFax", DbType="Char(15)")]
		public string ResFax
		{
			get
			{
				return this._ResFax;
			}
			set
			{
				if ((this._ResFax != value))
				{
					this.OnResFaxChanging(value);
					this.SendPropertyChanging();
					this._ResFax = value;
					this.SendPropertyChanged("ResFax");
					this.OnResFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResResPor", DbType="Char(20)")]
		public string ResResPor
		{
			get
			{
				return this._ResResPor;
			}
			set
			{
				if ((this._ResResPor != value))
				{
					this.OnResResPorChanging(value);
					this.SendPropertyChanging();
					this._ResResPor = value;
					this.SendPropertyChanged("ResResPor");
					this.OnResResPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFecEnt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResFecEnt
		{
			get
			{
				return this._ResFecEnt;
			}
			set
			{
				if ((this._ResFecEnt != value))
				{
					this.OnResFecEntChanging(value);
					this.SendPropertyChanging();
					this._ResFecEnt = value;
					this.SendPropertyChanged("ResFecEnt");
					this.OnResFecEntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFecSal", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResFecSal
		{
			get
			{
				return this._ResFecSal;
			}
			set
			{
				if ((this._ResFecSal != value))
				{
					this.OnResFecSalChanging(value);
					this.SendPropertyChanging();
					this._ResFecSal = value;
					this.SendPropertyChanged("ResFecSal");
					this.OnResFecSalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResEsta", DbType="Char(8)")]
		public string ResEsta
		{
			get
			{
				return this._ResEsta;
			}
			set
			{
				if ((this._ResEsta != value))
				{
					this.OnResEstaChanging(value);
					this.SendPropertyChanging();
					this._ResEsta = value;
					this.SendPropertyChanged("ResEsta");
					this.OnResEstaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResProced", DbType="Char(15)")]
		public string ResProced
		{
			get
			{
				return this._ResProced;
			}
			set
			{
				if ((this._ResProced != value))
				{
					this.OnResProcedChanging(value);
					this.SendPropertyChanging();
					this._ResProced = value;
					this.SendPropertyChanged("ResProced");
					this.OnResProcedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RHConLin", DbType="SmallInt")]
		public System.Nullable<short> RHConLin
		{
			get
			{
				return this._RHConLin;
			}
			set
			{
				if ((this._RHConLin != value))
				{
					this.OnRHConLinChanging(value);
					this.SendPropertyChanging();
					this._RHConLin = value;
					this.SendPropertyChanged("RHConLin");
					this.OnRHConLinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResPlan", DbType="Char(5)")]
		public string ResPlan
		{
			get
			{
				return this._ResPlan;
			}
			set
			{
				if ((this._ResPlan != value))
				{
					this.OnResPlanChanging(value);
					this.SendPropertyChanging();
					this._ResPlan = value;
					this.SendPropertyChanged("ResPlan");
					this.OnResPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResConSen", DbType="SmallInt")]
		public System.Nullable<short> ResConSen
		{
			get
			{
				return this._ResConSen;
			}
			set
			{
				if ((this._ResConSen != value))
				{
					this.OnResConSenChanging(value);
					this.SendPropertyChanging();
					this._ResConSen = value;
					this.SendPropertyChanged("ResConSen");
					this.OnResConSenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResConfirm", DbType="Char(1)")]
		public System.Nullable<char> ResConfirm
		{
			get
			{
				return this._ResConfirm;
			}
			set
			{
				if ((this._ResConfirm != value))
				{
					this.OnResConfirmChanging(value);
					this.SendPropertyChanging();
					this._ResConfirm = value;
					this.SendPropertyChanged("ResConfirm");
					this.OnResConfirmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFecConf", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResFecConf
		{
			get
			{
				return this._ResFecConf;
			}
			set
			{
				if ((this._ResFecConf != value))
				{
					this.OnResFecConfChanging(value);
					this.SendPropertyChanging();
					this._ResFecConf = value;
					this.SendPropertyChanged("ResFecConf");
					this.OnResFecConfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHorConf", DbType="Char(8)")]
		public string ResHorConf
		{
			get
			{
				return this._ResHorConf;
			}
			set
			{
				if ((this._ResHorConf != value))
				{
					this.OnResHorConfChanging(value);
					this.SendPropertyChanging();
					this._ResHorConf = value;
					this.SendPropertyChanged("ResHorConf");
					this.OnResHorConfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResMotCan", DbType="Char(60)")]
		public string ResMotCan
		{
			get
			{
				return this._ResMotCan;
			}
			set
			{
				if ((this._ResMotCan != value))
				{
					this.OnResMotCanChanging(value);
					this.SendPropertyChanging();
					this._ResMotCan = value;
					this.SendPropertyChanged("ResMotCan");
					this.OnResMotCanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResPorDto", DbType="SmallInt")]
		public System.Nullable<short> ResPorDto
		{
			get
			{
				return this._ResPorDto;
			}
			set
			{
				if ((this._ResPorDto != value))
				{
					this.OnResPorDtoChanging(value);
					this.SendPropertyChanging();
					this._ResPorDto = value;
					this.SendPropertyChanged("ResPorDto");
					this.OnResPorDtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescId", DbType="SmallInt")]
		public System.Nullable<short> DescId
		{
			get
			{
				return this._DescId;
			}
			set
			{
				if ((this._DescId != value))
				{
					this.OnDescIdChanging(value);
					this.SendPropertyChanging();
					this._DescId = value;
					this.SendPropertyChanged("DescId");
					this.OnDescIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResEmpPaga", DbType="Int")]
		public System.Nullable<int> ResEmpPaga
		{
			get
			{
				return this._ResEmpPaga;
			}
			set
			{
				if ((this._ResEmpPaga != value))
				{
					this.OnResEmpPagaChanging(value);
					this.SendPropertyChanging();
					this._ResEmpPaga = value;
					this.SendPropertyChanged("ResEmpPaga");
					this.OnResEmpPagaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResDestino", DbType="Char(15)")]
		public string ResDestino
		{
			get
			{
				return this._ResDestino;
			}
			set
			{
				if ((this._ResDestino != value))
				{
					this.OnResDestinoChanging(value);
					this.SendPropertyChanging();
					this._ResDestino = value;
					this.SendPropertyChanged("ResDestino");
					this.OnResDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResConRoo", DbType="Int")]
		public System.Nullable<int> ResConRoo
		{
			get
			{
				return this._ResConRoo;
			}
			set
			{
				if ((this._ResConRoo != value))
				{
					this.OnResConRooChanging(value);
					this.SendPropertyChanging();
					this._ResConRoo = value;
					this.SendPropertyChanged("ResConRoo");
					this.OnResConRooChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResTarifCar", DbType="Char(1)")]
		public System.Nullable<char> ResTarifCar
		{
			get
			{
				return this._ResTarifCar;
			}
			set
			{
				if ((this._ResTarifCar != value))
				{
					this.OnResTarifCarChanging(value);
					this.SendPropertyChanging();
					this._ResTarifCar = value;
					this.SendPropertyChanged("ResTarifCar");
					this.OnResTarifCarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResMonFact", DbType="SmallInt")]
		public System.Nullable<short> ResMonFact
		{
			get
			{
				return this._ResMonFact;
			}
			set
			{
				if ((this._ResMonFact != value))
				{
					this.OnResMonFactChanging(value);
					this.SendPropertyChanging();
					this._ResMonFact = value;
					this.SendPropertyChanged("ResMonFact");
					this.OnResMonFactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResCamMat", DbType="SmallInt")]
		public System.Nullable<short> ResCamMat
		{
			get
			{
				return this._ResCamMat;
			}
			set
			{
				if ((this._ResCamMat != value))
				{
					this.OnResCamMatChanging(value);
					this.SendPropertyChanging();
					this._ResCamMat = value;
					this.SendPropertyChanged("ResCamMat");
					this.OnResCamMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResCamSin", DbType="SmallInt")]
		public System.Nullable<short> ResCamSin
		{
			get
			{
				return this._ResCamSin;
			}
			set
			{
				if ((this._ResCamSin != value))
				{
					this.OnResCamSinChanging(value);
					this.SendPropertyChanging();
					this._ResCamSin = value;
					this.SendPropertyChanged("ResCamSin");
					this.OnResCamSinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResCamCun", DbType="SmallInt")]
		public System.Nullable<short> ResCamCun
		{
			get
			{
				return this._ResCamCun;
			}
			set
			{
				if ((this._ResCamCun != value))
				{
					this.OnResCamCunChanging(value);
					this.SendPropertyChanging();
					this._ResCamCun = value;
					this.SendPropertyChanged("ResCamCun");
					this.OnResCamCunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHoraEntrada", DbType="Char(8)")]
		public string ResHoraEntrada
		{
			get
			{
				return this._ResHoraEntrada;
			}
			set
			{
				if ((this._ResHoraEntrada != value))
				{
					this.OnResHoraEntradaChanging(value);
					this.SendPropertyChanging();
					this._ResHoraEntrada = value;
					this.SendPropertyChanged("ResHoraEntrada");
					this.OnResHoraEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResGruId", DbType="Char(8)")]
		public string ResGruId
		{
			get
			{
				return this._ResGruId;
			}
			set
			{
				if ((this._ResGruId != value))
				{
					this.OnResGruIdChanging(value);
					this.SendPropertyChanging();
					this._ResGruId = value;
					this.SendPropertyChanged("ResGruId");
					this.OnResGruIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeViaId", DbType="Int")]
		public System.Nullable<int> AgeViaId
		{
			get
			{
				return this._AgeViaId;
			}
			set
			{
				if ((this._AgeViaId != value))
				{
					this.OnAgeViaIdChanging(value);
					this.SendPropertyChanging();
					this._AgeViaId = value;
					this.SendPropertyChanged("AgeViaId");
					this.OnAgeViaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResCambioDatAgencia", DbType="Char(1)")]
		public System.Nullable<char> ResCambioDatAgencia
		{
			get
			{
				return this._ResCambioDatAgencia;
			}
			set
			{
				if ((this._ResCambioDatAgencia != value))
				{
					this.OnResCambioDatAgenciaChanging(value);
					this.SendPropertyChanging();
					this._ResCambioDatAgencia = value;
					this.SendPropertyChanged("ResCambioDatAgencia");
					this.OnResCambioDatAgenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResPagaHospedaje", DbType="Int")]
		public System.Nullable<int> ResPagaHospedaje
		{
			get
			{
				return this._ResPagaHospedaje;
			}
			set
			{
				if ((this._ResPagaHospedaje != value))
				{
					this.OnResPagaHospedajeChanging(value);
					this.SendPropertyChanging();
					this._ResPagaHospedaje = value;
					this.SendPropertyChanged("ResPagaHospedaje");
					this.OnResPagaHospedajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFecEntHor", DbType="Char(8)")]
		public string ResFecEntHor
		{
			get
			{
				return this._ResFecEntHor;
			}
			set
			{
				if ((this._ResFecEntHor != value))
				{
					this.OnResFecEntHorChanging(value);
					this.SendPropertyChanging();
					this._ResFecEntHor = value;
					this.SendPropertyChanged("ResFecEntHor");
					this.OnResFecEntHorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResMucLinObs", DbType="SmallInt")]
		public System.Nullable<short> ResMucLinObs
		{
			get
			{
				return this._ResMucLinObs;
			}
			set
			{
				if ((this._ResMucLinObs != value))
				{
					this.OnResMucLinObsChanging(value);
					this.SendPropertyChanging();
					this._ResMucLinObs = value;
					this.SendPropertyChanged("ResMucLinObs");
					this.OnResMucLinObsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResMail", DbType="Char(50)")]
		public string ResMail
		{
			get
			{
				return this._ResMail;
			}
			set
			{
				if ((this._ResMail != value))
				{
					this.OnResMailChanging(value);
					this.SendPropertyChanging();
					this._ResMail = value;
					this.SendPropertyChanged("ResMail");
					this.OnResMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHabiaSenia", DbType="Char(1)")]
		public System.Nullable<char> ResHabiaSenia
		{
			get
			{
				return this._ResHabiaSenia;
			}
			set
			{
				if ((this._ResHabiaSenia != value))
				{
					this.OnResHabiaSeniaChanging(value);
					this.SendPropertyChanging();
					this._ResHabiaSenia = value;
					this.SendPropertyChanged("ResHabiaSenia");
					this.OnResHabiaSeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHisHabNumAnt", DbType="SmallInt")]
		public System.Nullable<short> ResHisHabNumAnt
		{
			get
			{
				return this._ResHisHabNumAnt;
			}
			set
			{
				if ((this._ResHisHabNumAnt != value))
				{
					this.OnResHisHabNumAntChanging(value);
					this.SendPropertyChanging();
					this._ResHisHabNumAnt = value;
					this.SendPropertyChanged("ResHisHabNumAnt");
					this.OnResHisHabNumAntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHisTarIdAnt", DbType="Char(5)")]
		public string ResHisTarIdAnt
		{
			get
			{
				return this._ResHisTarIdAnt;
			}
			set
			{
				if ((this._ResHisTarIdAnt != value))
				{
					this.OnResHisTarIdAntChanging(value);
					this.SendPropertyChanging();
					this._ResHisTarIdAnt = value;
					this.SendPropertyChanged("ResHisTarIdAnt");
					this.OnResHisTarIdAntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHisTarMonIdAnt", DbType="SmallInt")]
		public System.Nullable<short> ResHisTarMonIdAnt
		{
			get
			{
				return this._ResHisTarMonIdAnt;
			}
			set
			{
				if ((this._ResHisTarMonIdAnt != value))
				{
					this.OnResHisTarMonIdAntChanging(value);
					this.SendPropertyChanging();
					this._ResHisTarMonIdAnt = value;
					this.SendPropertyChanged("ResHisTarMonIdAnt");
					this.OnResHisTarMonIdAntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHisTarImporteAnt", DbType="Money")]
		public System.Nullable<decimal> ResHisTarImporteAnt
		{
			get
			{
				return this._ResHisTarImporteAnt;
			}
			set
			{
				if ((this._ResHisTarImporteAnt != value))
				{
					this.OnResHisTarImporteAntChanging(value);
					this.SendPropertyChanging();
					this._ResHisTarImporteAnt = value;
					this.SendPropertyChanged("ResHisTarImporteAnt");
					this.OnResHisTarImporteAntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResConfPorMail", DbType="Char(1)")]
		public System.Nullable<char> ResConfPorMail
		{
			get
			{
				return this._ResConfPorMail;
			}
			set
			{
				if ((this._ResConfPorMail != value))
				{
					this.OnResConfPorMailChanging(value);
					this.SendPropertyChanging();
					this._ResConfPorMail = value;
					this.SendPropertyChanged("ResConfPorMail");
					this.OnResConfPorMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResEMailId", DbType="Int")]
		public System.Nullable<int> ResEMailId
		{
			get
			{
				return this._ResEMailId;
			}
			set
			{
				if ((this._ResEMailId != value))
				{
					this.OnResEMailIdChanging(value);
					this.SendPropertyChanging();
					this._ResEMailId = value;
					this.SendPropertyChanged("ResEMailId");
					this.OnResEMailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResDesAplicableA", DbType="Char(1)")]
		public System.Nullable<char> ResDesAplicableA
		{
			get
			{
				return this._ResDesAplicableA;
			}
			set
			{
				if ((this._ResDesAplicableA != value))
				{
					this.OnResDesAplicableAChanging(value);
					this.SendPropertyChanging();
					this._ResDesAplicableA = value;
					this.SendPropertyChanged("ResDesAplicableA");
					this.OnResDesAplicableAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResCantPax", DbType="SmallInt")]
		public System.Nullable<short> ResCantPax
		{
			get
			{
				return this._ResCantPax;
			}
			set
			{
				if ((this._ResCantPax != value))
				{
					this.OnResCantPaxChanging(value);
					this.SendPropertyChanging();
					this._ResCantPax = value;
					this.SendPropertyChanged("ResCantPax");
					this.OnResCantPaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipOcuId", DbType="Int")]
		public System.Nullable<int> TipOcuId
		{
			get
			{
				return this._TipOcuId;
			}
			set
			{
				if ((this._TipOcuId != value))
				{
					this.OnTipOcuIdChanging(value);
					this.SendPropertyChanging();
					this._TipOcuId = value;
					this.SendPropertyChanged("TipOcuId");
					this.OnTipOcuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFichaDeIngreso", DbType="Char(1)")]
		public System.Nullable<char> ResFichaDeIngreso
		{
			get
			{
				return this._ResFichaDeIngreso;
			}
			set
			{
				if ((this._ResFichaDeIngreso != value))
				{
					this.OnResFichaDeIngresoChanging(value);
					this.SendPropertyChanging();
					this._ResFichaDeIngreso = value;
					this.SendPropertyChanged("ResFichaDeIngreso");
					this.OnResFichaDeIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResMotivoAlojamiento", DbType="Char(80)")]
		public string ResMotivoAlojamiento
		{
			get
			{
				return this._ResMotivoAlojamiento;
			}
			set
			{
				if ((this._ResMotivoAlojamiento != value))
				{
					this.OnResMotivoAlojamientoChanging(value);
					this.SendPropertyChanging();
					this._ResMotivoAlojamiento = value;
					this.SendPropertyChanged("ResMotivoAlojamiento");
					this.OnResMotivoAlojamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResLateCheckOut", DbType="Char(1)")]
		public System.Nullable<char> ResLateCheckOut
		{
			get
			{
				return this._ResLateCheckOut;
			}
			set
			{
				if ((this._ResLateCheckOut != value))
				{
					this.OnResLateCheckOutChanging(value);
					this.SendPropertyChanging();
					this._ResLateCheckOut = value;
					this.SendPropertyChanged("ResLateCheckOut");
					this.OnResLateCheckOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResDesayunos", DbType="SmallInt")]
		public System.Nullable<short> ResDesayunos
		{
			get
			{
				return this._ResDesayunos;
			}
			set
			{
				if ((this._ResDesayunos != value))
				{
					this.OnResDesayunosChanging(value);
					this.SendPropertyChanging();
					this._ResDesayunos = value;
					this.SendPropertyChanged("ResDesayunos");
					this.OnResDesayunosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResVoucherAgencia", DbType="Char(10)")]
		public string ResVoucherAgencia
		{
			get
			{
				return this._ResVoucherAgencia;
			}
			set
			{
				if ((this._ResVoucherAgencia != value))
				{
					this.OnResVoucherAgenciaChanging(value);
					this.SendPropertyChanging();
					this._ResVoucherAgencia = value;
					this.SendPropertyChanged("ResVoucherAgencia");
					this.OnResVoucherAgenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResCanFacIdNoShow", DbType="Int")]
		public System.Nullable<int> ResCanFacIdNoShow
		{
			get
			{
				return this._ResCanFacIdNoShow;
			}
			set
			{
				if ((this._ResCanFacIdNoShow != value))
				{
					this.OnResCanFacIdNoShowChanging(value);
					this.SendPropertyChanging();
					this._ResCanFacIdNoShow = value;
					this.SendPropertyChanged("ResCanFacIdNoShow");
					this.OnResCanFacIdNoShowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResCanNoShow", DbType="Char(1)")]
		public System.Nullable<char> ResCanNoShow
		{
			get
			{
				return this._ResCanNoShow;
			}
			set
			{
				if ((this._ResCanNoShow != value))
				{
					this.OnResCanNoShowChanging(value);
					this.SendPropertyChanging();
					this._ResCanNoShow = value;
					this.SendPropertyChanged("ResCanNoShow");
					this.OnResCanNoShowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResSeniaUtilizada", DbType="Money")]
		public System.Nullable<decimal> ResSeniaUtilizada
		{
			get
			{
				return this._ResSeniaUtilizada;
			}
			set
			{
				if ((this._ResSeniaUtilizada != value))
				{
					this.OnResSeniaUtilizadaChanging(value);
					this.SendPropertyChanging();
					this._ResSeniaUtilizada = value;
					this.SendPropertyChanged("ResSeniaUtilizada");
					this.OnResSeniaUtilizadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResAutoMatricula", DbType="Char(10)")]
		public string ResAutoMatricula
		{
			get
			{
				return this._ResAutoMatricula;
			}
			set
			{
				if ((this._ResAutoMatricula != value))
				{
					this.OnResAutoMatriculaChanging(value);
					this.SendPropertyChanging();
					this._ResAutoMatricula = value;
					this.SendPropertyChanged("ResAutoMatricula");
					this.OnResAutoMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResAutoColor", DbType="Char(50)")]
		public string ResAutoColor
		{
			get
			{
				return this._ResAutoColor;
			}
			set
			{
				if ((this._ResAutoColor != value))
				{
					this.OnResAutoColorChanging(value);
					this.SendPropertyChanging();
					this._ResAutoColor = value;
					this.SendPropertyChanged("ResAutoColor");
					this.OnResAutoColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResAutoModelo", DbType="Char(50)")]
		public string ResAutoModelo
		{
			get
			{
				return this._ResAutoModelo;
			}
			set
			{
				if ((this._ResAutoModelo != value))
				{
					this.OnResAutoModeloChanging(value);
					this.SendPropertyChanging();
					this._ResAutoModelo = value;
					this.SendPropertyChanged("ResAutoModelo");
					this.OnResAutoModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResAutoMarca", DbType="Char(50)")]
		public string ResAutoMarca
		{
			get
			{
				return this._ResAutoMarca;
			}
			set
			{
				if ((this._ResAutoMarca != value))
				{
					this.OnResAutoMarcaChanging(value);
					this.SendPropertyChanging();
					this._ResAutoMarca = value;
					this.SendPropertyChanged("ResAutoMarca");
					this.OnResAutoMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFechaConfirmacionMovible", DbType="Char(1)")]
		public System.Nullable<char> ResFechaConfirmacionMovible
		{
			get
			{
				return this._ResFechaConfirmacionMovible;
			}
			set
			{
				if ((this._ResFechaConfirmacionMovible != value))
				{
					this.OnResFechaConfirmacionMovibleChanging(value);
					this.SendPropertyChanging();
					this._ResFechaConfirmacionMovible = value;
					this.SendPropertyChanged("ResFechaConfirmacionMovible");
					this.OnResFechaConfirmacionMovibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFechaConfirmacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResFechaConfirmacion
		{
			get
			{
				return this._ResFechaConfirmacion;
			}
			set
			{
				if ((this._ResFechaConfirmacion != value))
				{
					this.OnResFechaConfirmacionChanging(value);
					this.SendPropertyChanging();
					this._ResFechaConfirmacion = value;
					this.SendPropertyChanged("ResFechaConfirmacion");
					this.OnResFechaConfirmacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResMaqVer", DbType="Char(20)")]
		public string ResMaqVer
		{
			get
			{
				return this._ResMaqVer;
			}
			set
			{
				if ((this._ResMaqVer != value))
				{
					this.OnResMaqVerChanging(value);
					this.SendPropertyChanging();
					this._ResMaqVer = value;
					this.SendPropertyChanged("ResMaqVer");
					this.OnResMaqVerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResUsuVer", DbType="Char(10)")]
		public string ResUsuVer
		{
			get
			{
				return this._ResUsuVer;
			}
			set
			{
				if ((this._ResUsuVer != value))
				{
					this.OnResUsuVerChanging(value);
					this.SendPropertyChanging();
					this._ResUsuVer = value;
					this.SendPropertyChanged("ResUsuVer");
					this.OnResUsuVerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResHorVer", DbType="Char(8)")]
		public string ResHorVer
		{
			get
			{
				return this._ResHorVer;
			}
			set
			{
				if ((this._ResHorVer != value))
				{
					this.OnResHorVerChanging(value);
					this.SendPropertyChanging();
					this._ResHorVer = value;
					this.SendPropertyChanged("ResHorVer");
					this.OnResHorVerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResFecVer", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResFecVer
		{
			get
			{
				return this._ResFecVer;
			}
			set
			{
				if ((this._ResFecVer != value))
				{
					this.OnResFecVerChanging(value);
					this.SendPropertyChanging();
					this._ResFecVer = value;
					this.SendPropertyChanged("ResFecVer");
					this.OnResFecVerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResVerificada", DbType="Char(1)")]
		public System.Nullable<char> ResVerificada
		{
			get
			{
				return this._ResVerificada;
			}
			set
			{
				if ((this._ResVerificada != value))
				{
					this.OnResVerificadaChanging(value);
					this.SendPropertyChanging();
					this._ResVerificada = value;
					this.SendPropertyChanged("ResVerificada");
					this.OnResVerificadaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
